services:
   mongod:
      image: mongodb/mongodb-community-server:8.2.1-ubi9
      container_name: mongod-community
      command: >-
         mongod
         --config /etc/mongod.conf
      ports:
         - 27017:27017
      extra_hosts:
         - "host.docker.internal:host-gateway"
      environment:
         - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
         - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
         - MONGODB_MONGOTUSER_PASSWORD=${MONGODB_MONGOTUSER_PASSWORD}
      env_file:
         - .env
      volumes:
         - mongod_data:/data/db
         - ./mongod.conf:/etc/mongod.conf:ro
         - ./sampledata.archive:/sampledata.archive
         - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
         - ./rs0.key:/keyfile:ro
      networks:
         - search-community


   mongot:
      image: mongodb/mongodb-community-search:latest
      container_name: mongot-community-search
      networks:
         - search-community
      volumes:
         - mongot_data:/data/mongot
         - ./mongot.conf:/mongot-community/config.default.yml
         - ./pwfile:/mongot-community/pwfile:ro
      depends_on:
         - mongod
      ports:
         - 27028:27028  # Query server port from config
         - 9946:9946    # Metrics port from config

volumes:
   mongod_data:
   mongot_data:

networks:
   search-community:
      name: search-community
      external: true  # Use an external network if it exists. Comment this line if you want to create a new network.