services:
   mongod:
      image: mongodb/mongodb-community-server:latest
      container_name: mongod-community
      command: >-
         mongod
         --config /etc/mongod.conf
         --replSetMember=mongod.search-community:27017
      ports:
         - 27017:27017
      extra_hosts:
         - "host.docker.internal:host-gateway"
      volumes:
         - mongod_data:/data/db
         - ./mongod.conf:/etc/mongod.conf:ro
         - ./rs0.key:/etc/mongo-keyfile:ro
         - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      networks:
         - search-community
      environment:
         - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
         - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
         - MONGODB_MONGOTUSER_PASSWORD=${MONGODB_MONGOTUSER_PASSWORD}
      healthcheck:
         test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
         interval: 30s
         timeout: 10s
         retries: 3

   mongot:
      image: mongodb/mongodb-community-search:latest
      container_name: mongot-community-pupr
      networks:
         - search-community
      volumes:
         - mongot_data:/data/mongot
         - ./mongot.conf:/mongot-community/config.default.yml
         - ./pwfile:/mongot-community/pwfile:ro
      depends_on:
         mongod:
            condition: service_healthy
      ports:
         - 27028:27028  # Query server port from config
         - 9946:9946    # Metrics port from config

volumes:
   mongod_data:
   mongot_data:

networks:
   search-community:
      name: search-community
      # external: true  # Use an external network if it exists. Comment this line if you want to create a new network.